- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v4
  with:
    publish_dir: ./dist
    publish_branch: gh-pages
    cname: danfinds.store
    user_name: "github-actions[bot]"
    user_email: "github-actions[bot]@users.noreply.github.com"
    personal_token: ${{ secrets.GH_PAT }}
